version: '3'
services:
    brain:
        build: .
        ports:
            - "8081:8081"
        volumes:
            - .:/app
    mongo:
        image: "mongo:latest"
        volumes:
            - ./mongo_data:/data/db
